# Generated by Django 5.0.3 on 2024-03-05 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категории (просто чтобы были)',
                'verbose_name_plural': 'Категории (просто чтобы были)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Был удалён')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='authorization.category')),
            ],
            options={
                'verbose_name': 'Зарегистрированные пользователи',
                'verbose_name_plural': 'Зарегистрированные пользователи',
                'ordering': ['-date_creation'],
            },
        ),
    ]
