# Generated by Django 5.0.2 on 2024-03-08 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='authorization',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='NAMEEEEE'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authorization.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='login',
            field=models.CharField(max_length=15, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Пароль'),
        ),
    ]
